In [22]:
import librosa
import numpy as np
import matplotlib.pyplot as plt
import pretty_midi

from data_preprocessing import generate_train_data

In [23]:
audio = 'wav-folder/updown.wav'
midi = 'midi-folder/updown.mid'

sampling_rate = 16000
hop_length = 512
n_bins = 88

cqt, labels = generate_train_data(audio, sampling_rate, hop_length, n_bins, midi, False)



generating data...
cqt time - 55.168
midi time - 55.17189517746514
cqt frames - 1724
midi frames - 1724
done


In [33]:
import numpy as np

def group_cqt_frames(cqt, num_frames_before=3, num_frames_after=3):
    num_keys, num_frames = cqt.shape
    grouped_cqt_frames = []

    for i in range(num_frames):
        start_frame = max(0, i - num_frames_before)
        end_frame = min(num_frames, i + num_frames_after + 1)
        print(start_frame)
        print(end_frame)
        grouped_frame = cqt[:, start_frame:end_frame]
        print(grouped_frame)

        if end_frame-start_frame <= num_frames_before:
            if start_frame == 0:
                pass
                #wypelnic pierwsze iles tam klatek zerami...
            if end_frame == num_frames:
        
        # # Pad or truncate the grouped frame to ensure it has the same length
        # if grouped_frame.shape[1] < (num_frames_before + num_frames_after + 1):
        #     # Pad the frame with zeros if it's shorter
        #     pad_width = ((0, 0), (0, (num_frames_before + num_frames_after + 1) - grouped_frame.shape[1]))
        #     grouped_frame = np.pad(grouped_frame, pad_width, mode='constant')
        # elif grouped_frame.shape[1] > (num_frames_before + num_frames_after + 1):
        #     # Truncate the frame if it's longer
        #     grouped_frame = grouped_frame[:, :num_frames_before + num_frames_after + 1]
        
        
        grouped_cqt_frames.append(grouped_frame)

    # Stack the arrays along a new axis to form a 3D array
    # TWORZENIE NUMPY ARRAY - MUSZA BYC ROWNE WYMIARY (DLATEGO TRZEBA WYPELNIAC)
    # grouped_cqt_array = np.stack(grouped_cqt_frames, axis=-1)
    # return grouped_cqt_array

    return grouped_cqt_frames

IndentationError: expected an indented block after 'if' statement on line 19 (675739667.py, line 31)

In [35]:

# Mock CQT array (whole, small numbers from 0-10)
mock_cqt = np.random.randint(0, 5, size=(3, 7))  # 3 keys, 7 frames

# Test the function with the mock CQT array
grouped_cqt = group_cqt_frames(mock_cqt, num_frames_after=3, num_frames_before=3)

# Print the original and grouped CQT arrays for verification
print("Original CQT array:")
print(mock_cqt)

print("\nGrouped CQT array:")
print(grouped_cqt)

0
4
[[3 0 4 0]
 [2 0 1 0]
 [3 4 3 1]]
0
5
[[3 0 4 0 2]
 [2 0 1 0 2]
 [3 4 3 1 0]]
0
6
[[3 0 4 0 2 2]
 [2 0 1 0 2 1]
 [3 4 3 1 0 0]]
0
7
[[3 0 4 0 2 2 2]
 [2 0 1 0 2 1 2]
 [3 4 3 1 0 0 1]]
1
7
[[0 4 0 2 2 2]
 [0 1 0 2 1 2]
 [4 3 1 0 0 1]]
2
7
[[4 0 2 2 2]
 [1 0 2 1 2]
 [3 1 0 0 1]]
3
7
[[0 2 2 2]
 [0 2 1 2]
 [1 0 0 1]]
Original CQT array:
[[3 0 4 0 2 2 2]
 [2 0 1 0 2 1 2]
 [3 4 3 1 0 0 1]]

Grouped CQT array:
[array([[3, 0, 4, 0],
       [2, 0, 1, 0],
       [3, 4, 3, 1]]), array([[3, 0, 4, 0, 2],
       [2, 0, 1, 0, 2],
       [3, 4, 3, 1, 0]]), array([[3, 0, 4, 0, 2, 2],
       [2, 0, 1, 0, 2, 1],
       [3, 4, 3, 1, 0, 0]]), array([[3, 0, 4, 0, 2, 2, 2],
       [2, 0, 1, 0, 2, 1, 2],
       [3, 4, 3, 1, 0, 0, 1]]), array([[0, 4, 0, 2, 2, 2],
       [0, 1, 0, 2, 1, 2],
       [4, 3, 1, 0, 0, 1]]), array([[4, 0, 2, 2, 2],
       [1, 0, 2, 1, 2],
       [3, 1, 0, 0, 1]]), array([[0, 2, 2, 2],
       [0, 2, 1, 2],
       [1, 0, 0, 1]])]
