In [68]:
import numpy as np

In [69]:
# a = np.ndarray([[1,2,3],[[4,5,6], [2,3,4]]])
b = np.array([[[0,0,0],[9,9,9]] ,[[0,0,0],[9,9,9]]])

In [70]:
b.shape

(2, 2, 3)

In [71]:
c = []

In [72]:
c.extend(b)
c.extend(b)

# c.append(b)
# c.append(b)

In [73]:
c

[array([[0, 0, 0],
        [9, 9, 9]]),
 array([[0, 0, 0],
        [9, 9, 9]]),
 array([[0, 0, 0],
        [9, 9, 9]]),
 array([[0, 0, 0],
        [9, 9, 9]])]

In [74]:
d = np.array(c)

In [75]:
d.shape

(4, 2, 3)